version: 2.1

defaults: &defaults
  working_directory: /tmp/persist_to_workspace

orbs:
  aws-s3: circleci/aws-s3@1.0.15

jobs:

  test:
    <<: *defaults
    docker:
      - image: cimg/go:1.18

    steps:
      - checkout
      - run:
          name: run tests tools
          command: make test test-examples
      - persist_to_workspace:
          root: /tmp/persist_to_workspace
          paths:
            - .

workflows:
  version: 2

  pipeline:
    jobs:
      - test
